#!/bin/sh
# extract package version for marketplace dashboard
export CBSD_PWD=/var/empty
export NOCOLOR=1

ver=$( cbsd jexec jname=jupyterlab <<EOF
su - jupyter -c "/usr/local/bin/pip list" | awk '/jupyterlab /{print $2}'
EOF
)

if [ -n "${ver}" ]; then
	echo "${ver}" | /usr/bin/awk '{printf $2}'
else
	echo "unknown"
fi

exit 0
