#!/bin/sh
# extract package version for marketplace dashboard
export CBSD_PWD=/var/empty
export NOCOLOR=1

ver=$( cbsd jexec jname=pla <<EOF
grep 'define("VERSION",' /usr/local/www/pla/index.php | tr '"();,' ' '
EOF
)

if [ -n "${ver}" ]; then
	echo "${ver}" | /usr/bin/awk '{printf $3}'
else
	echo "unknown"
fi

exit 0
