#!/bin/sh
# extract package version for marketplace dashboard
export CBSD_PWD=/var/empty
export NOCOLOR=1

ver=$( cbsd jexec jname=clickhouse <<EOF
export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
clickhouse-server --version | tr -d [:alpha:] | awk '{printf $1}'
EOF
)

if [ -n "${ver}" ]; then
	echo "${ver}" | /usr/bin/awk '{printf $1}'
else
	echo "unknown"
fi

exit 0
